language: c
dist: trusty
env:
  - BD=arduino:avr:uno
  - BD=arduino:avr:mega:cpu=atmega2560
  - BD=esp8266:esp8266:nodemcuv2:CpuFrequency=80,FlashSize=4M3M
  - BD=esp8266:esp8266:d1_mini:CpuFrequency=80,FlashSize=4M3M
  - BD=espressif:arduino-esp32:esp32doit-devkit-v1:FlashFreq=80,DebugLevel=none
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - sudo mv arduino-1.8.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/OpenMQTTGateway
  - rm /usr/local/share/arduino/OpenMQTTGateway/User_config.h
  - cp /usr/local/share/arduino/OpenMQTTGateway/tests/Test_config.h /usr/local/share/arduino/OpenMQTTGateway/User_config.h
  - wget https://github.com/z3t0/Arduino-IRremote/archive/2.1.0.zip -O /tmp/IRremote.zip
  - unzip /tmp/IRremote.zip -d /usr/local/share/arduino/libraries
  - rm -rf /usr/local/share/arduino/libraries/RobotIRremote
  - wget https://github.com/markszabo/IRremoteESP8266/archive/v2.2.0.zip -O /tmp/IRremoteESP8266.zip 
  - unzip /tmp/IRremoteESP8266.zip -d /usr/local/share/arduino/libraries
  - git clone https://github.com/ekstrand/ESP8266wifi /usr/local/share/arduino/libraries/ESP8266wifi
  - git clone https://github.com/1technophile/NewRemoteSwitch /usr/local/share/arduino/libraries/NewRemoteSwitch
  - wget https://github.com/knolleary/pubsubclient/archive/v2.6.zip -O /tmp/pubsubclient.zip
  - unzip /tmp/pubsubclient.zip -d /usr/local/share/arduino/libraries
  - wget https://github.com/sui77/rc-switch/archive/2.6.2.zip -O /tmp/rcswitch.zip
  - unzip /tmp/rcswitch.zip -d /usr/local/share/arduino/libraries
  - git clone https://github.com/arduino/arduinoOTA.git /usr/local/share/arduino/libraries/ArduinoOTA
  - git clone https://github.com/mrdunk/esp8266_mdns.git /usr/local/share/arduino/libraries/ESP8266mDNS
  - git clone https://github.com/adafruit/DHT-sensor-library /usr/local/share/arduino/libraries/DHT_sensor_library
  - git clone https://github.com/adafruit/Adafruit_Sensor /usr/local/share/arduino/libraries/Adafruit_Sensor
  - git clone https://github.com/sparkfun/SparkFun_BME280_Arduino_Library /usr/local/share/arduino/libraries/SparkFun_BME280
  - git clone https://github.com/LowPowerLab/RFM69 /usr/local/share/arduino/libraries/RFM69
  - rm /usr/local/share/arduino/libraries/RFM69/RFM69_OTA.h
  - rm /usr/local/share/arduino/libraries/RFM69/RFM69_OTA.cpp
  - git clone https://github.com/nkolban/ESP32_BLE_Arduino /usr/local/share/arduino/libraries/ESP32_BLE_Arduino
  - mkdir -p hardware/espressif
  - cd hardware/espressif
  - git clone https://github.com/espressif/arduino-esp32.git esp32
  - cd esp32/tools/
  - python get.py
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-boards esp8266:esp8266
  - arduino --board $BD --save-prefs
  - arduino --pref "compiler.warning_level=all" --save-prefs
script:
  - arduino --verify --board $BD $PWD/OpenMQTTGateway.ino
notifications:
  email:
    on_success: change
    on_failure: change
