language: c
dist: trusty
env:
  - BD=arduino:avr:uno
  - BD=arduino:avr:mega:cpu=atmega2560
  - BD=esp8266:esp8266:nodemcuv2:CpuFrequency=80,FlashSize=4M3M
  - BD=esp8266:esp8266:d1_mini:CpuFrequency=80,FlashSize=4M3M
  - BD=esp32:esp32:esp32:PartitionScheme=min_spiffs,FlashFreq=80
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - sudo mv arduino-$IDE_VERSION /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/OpenMQTTGateway
  - rm /usr/local/share/arduino/OpenMQTTGateway/User_config.h
  - cp /usr/local/share/arduino/OpenMQTTGateway/tests/Test_config.h /usr/local/share/arduino/OpenMQTTGateway/User_config.h
  - rm -rf /usr/local/share/arduino/libraries/RobotIRremote
  - cp -R /usr/local/share/arduino/OpenMQTTGateway/lib/. /usr/local/share/arduino/libraries
  - cd /usr/local/share/arduino/OpenMQTTGateway
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json,https://dl.espressif.com/dl/package_esp32_index.json" --save-prefs
  - if [[ "$BD" =~ "esp8266:esp8266:" ]]; then
      arduino --install-boards esp8266:esp8266:2.4.2;
    fi
  - if [[ "$BD" =~ "esp32:esp32:" ]]; then
      arduino --install-boards esp32:esp32;
    fi
script:
  - arduino --verify --board $BD $PWD/OpenMQTTGateway.ino
notifications:
  email:
    on_success: change
    on_failure: change
    